version: '3.8'

services:
  app:
    image: ntnguyen055/api-security-app:latest
    container_name: docapp_django
    restart: always
    # Lưu ý: Ta đổi ports thành expose để chỉ nội bộ Docker đọc được, không hở ra ngoài
    expose:
      - "8000"
    env_file:
    - /home/ubuntu/appointment-web/.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: docapp_redis
    restart: always

  gateway:
    image: openresty/openresty:alpine
    container_name: openresty_gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      # Đưa 2 file chứng chỉ thật vào trong OpenResty
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    depends_on:
      - app