version: '3.8'

services:

  app:
    image: ntnguyen055/api-security-app:latest
    container_name: docapp_django
    restart: unless-stopped

    expose:
      - "8000"

    env_file:
      - /home/ubuntu/appointment-web/.env

    depends_on:
      - redis

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

    networks:
      - internal


  redis:
    image: redis:7-alpine
    container_name: docapp_redis
    restart: unless-stopped

    command: >
      redis-server
      --maxmemory 50mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

    networks:
      - internal


  gateway:
    image: ntnguyen055/api-security-gateway:latest
    container_name: openresty_gateway
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:9145:9145"

    env_file:
      - /home/ubuntu/appointment-web/.env

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro

    depends_on:
      - app

    healthcheck:
      test: ["CMD", "curl", "-sf",
             "-A", "HealthChecker/1.0",
             "-H", "Host: dacn3.duckdns.org",
             "http://localhost/health/"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 15s

    networks:
      - internal

    ulimits:
      nofile:
        soft: 65535
        hard: 65535


# ================= NETWORK =================
networks:
  internal:
    driver: bridge